// <auto-generated />
using System;
using Chis_Denisa_Proiect1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Chis_Denisa_Proiect1.Migrations
{
    [DbContext(typeof(Chis_Denisa_Proiect1Context))]
    partial class Chis_Denisa_Proiect1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Chis_Denisa_Proiect1.Models.Doctor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumeDoctor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("Chis_Denisa_Proiect1.Models.Programare", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Animal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ID");

                    b.HasIndex("DoctorID");

                    b.ToTable("Programare");
                });

            modelBuilder.Entity("Chis_Denisa_Proiect1.Models.ProgramareServiciu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProgramareID")
                        .HasColumnType("int");

                    b.Property<int>("ServiciuID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProgramareID");

                    b.HasIndex("ServiciuID");

                    b.ToTable("ProgramareServiciu");
                });

            modelBuilder.Entity("Chis_Denisa_Proiect1.Models.Serviciu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumeServiciu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Serviciu");
                });

            modelBuilder.Entity("Chis_Denisa_Proiect1.Models.Programare", b =>
                {
                    b.HasOne("Chis_Denisa_Proiect1.Models.Doctor", "Doctor")
                        .WithMany("Programari")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Chis_Denisa_Proiect1.Models.ProgramareServiciu", b =>
                {
                    b.HasOne("Chis_Denisa_Proiect1.Models.Programare", "Programare")
                        .WithMany("ProgramareServicii")
                        .HasForeignKey("ProgramareID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chis_Denisa_Proiect1.Models.Serviciu", "Serviciu")
                        .WithMany("ProgramareServicii")
                        .HasForeignKey("ServiciuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programare");

                    b.Navigation("Serviciu");
                });

            modelBuilder.Entity("Chis_Denisa_Proiect1.Models.Doctor", b =>
                {
                    b.Navigation("Programari");
                });

            modelBuilder.Entity("Chis_Denisa_Proiect1.Models.Programare", b =>
                {
                    b.Navigation("ProgramareServicii");
                });

            modelBuilder.Entity("Chis_Denisa_Proiect1.Models.Serviciu", b =>
                {
                    b.Navigation("ProgramareServicii");
                });
#pragma warning restore 612, 618
        }
    }
}
